### ISSUE TITLE
configuration via UI not working with HA 2022.6.6

### ISSUE THREAD

**Issue by Armadill0** [nyffchanium/argoclima-integration#3]
## Version of the custom_component

Argoclima component: latest master
Home Assistant: 2022.6.6

## Configuration

none

## Describe the bug

Just tried to setup the integration through the Devices & Services page and got this:
![image](https://user-images.githubusercontent.com/6536990/174189819-643d1185-c75c-4e5f-9444-646a2ae0e31c.png)

Logs found:
```
Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 12:27:40 AM (3 occurrences)
Last logged: 12:29:44 AM

Error occurred loading configuration flow for integration argoclima: No module named 'custom_components.argoclima.api'
```

## Debug log

Haven't found more than the mentioned log above when setting:

```text
logger:
  logs:
    custom_components.argoclima: debug
```

**Comment by spali** [comment]
Just did setup the integration yesterday on 2022.6.6 and it worked as expected (dialog to enter ip address).
Maybe restart can help and checking the logs of HA for errors.

**Comment by nyffchanium** [comment]
Tested it with 2022.6.7 and had success. 

@Armadill0  Does it still not work for you?

Have you tried reinstalling the repo via HACS?

**Comment by Armadill0** [comment]
@nyffchanium Hi and thanks for your response. I was actually searching for it in HACS and couldn't find it before. After removing the manual install and finding it in HACS today it worked. Thanks for the hint! :+1:
